/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as CountdownGameContractJson } from "../CountdownGame.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";

// Custom types for the contract
export namespace CountdownGameTypes {
  export type Fields = {
    currentLeader: Address;
    currentPot: bigint;
    currentDurationMs: bigint;
    deadlineMs: bigint;
    nextRoundSeed: bigint;
    savingsPot: bigint;
    roundActive: boolean;
  };

  export type State = ContractState<Fields>;

  export type PlayedEvent = ContractEvent<{
    player: Address;
    roundPot: bigint;
    deadlineMs: bigint;
    durationMs: bigint;
  }>;
  export type RoundSettledEvent = ContractEvent<{
    winner: Address;
    winnerPayout: bigint;
    nextSeed: bigint;
    savingsAdded: bigint;
  }>;

  export interface CallMethodTable {
    play: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    settleExpiredRound: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    startRound: {
      params: CallContractParams<{ caller: Address; now: bigint }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    play: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    settleExpiredRound: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    startRound: {
      params: SignExecuteContractMethodParams<{ caller: Address; now: bigint }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  CountdownGameInstance,
  CountdownGameTypes.Fields
> {
  encodeFields(fields: CountdownGameTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      []
    );
  }

  eventIndex = { Played: 0, RoundSettled: 1 };
  consts = {
    PLAY_COST: BigInt("1000000000000000000"),
    INITIAL_DURATION_MS: BigInt("63891936000000"),
  };

  at(address: string): CountdownGameInstance {
    return new CountdownGameInstance(address);
  }

  tests = {
    play: async (
      params: Omit<
        TestContractParamsWithoutMaps<CountdownGameTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "play", params, getContractByCodeHash);
    },
    settleExpiredRound: async (
      params: Omit<
        TestContractParamsWithoutMaps<CountdownGameTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "settleExpiredRound",
        params,
        getContractByCodeHash
      );
    },
    startRound: async (
      params: TestContractParamsWithoutMaps<
        CountdownGameTypes.Fields,
        { caller: Address; now: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "startRound", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: CountdownGameTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const CountdownGame = new Factory(
  Contract.fromJson(
    CountdownGameContractJson,
    "",
    "494b178881827aaab6be75e4a4db4298c4bd6e52f3c943613067925c6c5c87ef",
    []
  )
);
registerContract(CountdownGame);

// Use this class to interact with the blockchain
export class CountdownGameInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<CountdownGameTypes.State> {
    return fetchContractState(CountdownGame, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribePlayedEvent(
    options: EventSubscribeOptions<CountdownGameTypes.PlayedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      CountdownGame.contract,
      this,
      options,
      "Played",
      fromCount
    );
  }

  subscribeRoundSettledEvent(
    options: EventSubscribeOptions<CountdownGameTypes.RoundSettledEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      CountdownGame.contract,
      this,
      options,
      "RoundSettled",
      fromCount
    );
  }

  subscribeAllEvents(
    options: EventSubscribeOptions<
      CountdownGameTypes.PlayedEvent | CountdownGameTypes.RoundSettledEvent
    >,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvents(
      CountdownGame.contract,
      this,
      options,
      fromCount
    );
  }

  view = {
    play: async (
      params?: CountdownGameTypes.CallMethodParams<"play">
    ): Promise<CountdownGameTypes.CallMethodResult<"play">> => {
      return callMethod(
        CountdownGame,
        this,
        "play",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    settleExpiredRound: async (
      params?: CountdownGameTypes.CallMethodParams<"settleExpiredRound">
    ): Promise<CountdownGameTypes.CallMethodResult<"settleExpiredRound">> => {
      return callMethod(
        CountdownGame,
        this,
        "settleExpiredRound",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    startRound: async (
      params: CountdownGameTypes.CallMethodParams<"startRound">
    ): Promise<CountdownGameTypes.CallMethodResult<"startRound">> => {
      return callMethod(
        CountdownGame,
        this,
        "startRound",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    play: async (
      params: CountdownGameTypes.SignExecuteMethodParams<"play">
    ): Promise<CountdownGameTypes.SignExecuteMethodResult<"play">> => {
      return signExecuteMethod(CountdownGame, this, "play", params);
    },
    settleExpiredRound: async (
      params: CountdownGameTypes.SignExecuteMethodParams<"settleExpiredRound">
    ): Promise<
      CountdownGameTypes.SignExecuteMethodResult<"settleExpiredRound">
    > => {
      return signExecuteMethod(
        CountdownGame,
        this,
        "settleExpiredRound",
        params
      );
    },
    startRound: async (
      params: CountdownGameTypes.SignExecuteMethodParams<"startRound">
    ): Promise<CountdownGameTypes.SignExecuteMethodResult<"startRound">> => {
      return signExecuteMethod(CountdownGame, this, "startRound", params);
    },
  };
}
