/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as CountdownBettingMarketContractJson } from "../CountdownBettingMarket.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";

import { RalphMap } from "@alephium/web3";

// Custom types for the contract
export namespace CountdownBettingMarketTypes {
  export type Fields = {
    game: HexString;
    carryOverPot: bigint;
  };

  export type State = ContractState<Fields>;

  export type BetPlacedEvent = ContractEvent<{
    roundId: bigint;
    bettor: Address;
    target: Address;
    amount: bigint;
  }>;
  export type RoundFinalizedEvent = ContractEvent<{
    roundId: bigint;
    winner: Address;
    totalPool: bigint;
  }>;
  export type ClaimedEvent = ContractEvent<{
    roundId: bigint;
    bettor: Address;
    target: Address;
    payout: bigint;
  }>;
  export type CarryOverRolledEvent = ContractEvent<{
    roundId: bigint;
    amount: bigint;
  }>;

  export interface CallMethodTable {
    placeBet: {
      params: CallContractParams<{
        roundId: bigint;
        target: Address;
        amount: bigint;
      }>;
      result: CallContractResult<null>;
    };
    finalizeRound: {
      params: CallContractParams<{ roundId: bigint }>;
      result: CallContractResult<null>;
    };
    claim: {
      params: CallContractParams<{ roundId: bigint }>;
      result: CallContractResult<null>;
    };
    getRoundPools: {
      params: CallContractParams<{ roundId: bigint; target: Address }>;
      result: CallContractResult<[bigint, bigint]>;
    };
    getUserBet: {
      params: CallContractParams<{ roundId: bigint; bettor: Address }>;
      result: CallContractResult<[boolean, Address, bigint]>;
    };
    quotePayout: {
      params: CallContractParams<{
        roundId: bigint;
        target: Address;
        amount: bigint;
      }>;
      result: CallContractResult<bigint>;
    };
    getClaimablePayout: {
      params: CallContractParams<{
        roundId: bigint;
        target: Address;
        betAmount: bigint;
      }>;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    placeBet: {
      params: SignExecuteContractMethodParams<{
        roundId: bigint;
        target: Address;
        amount: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    finalizeRound: {
      params: SignExecuteContractMethodParams<{ roundId: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    claim: {
      params: SignExecuteContractMethodParams<{ roundId: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    getRoundPools: {
      params: SignExecuteContractMethodParams<{
        roundId: bigint;
        target: Address;
      }>;
      result: SignExecuteScriptTxResult;
    };
    getUserBet: {
      params: SignExecuteContractMethodParams<{
        roundId: bigint;
        bettor: Address;
      }>;
      result: SignExecuteScriptTxResult;
    };
    quotePayout: {
      params: SignExecuteContractMethodParams<{
        roundId: bigint;
        target: Address;
        amount: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    getClaimablePayout: {
      params: SignExecuteContractMethodParams<{
        roundId: bigint;
        target: Address;
        betAmount: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];

  export type Maps = {
    totalPoolByRound?: Map<HexString, bigint>;
    poolByRoundAndTarget?: Map<HexString, bigint>;
    userBetByRoundAndBettor?: Map<HexString, bigint>;
    userTargetByRoundAndBettor?: Map<HexString, Address>;
    winnerByRound?: Map<HexString, Address>;
    bettorCountByRound?: Map<HexString, bigint>;
  };
}

class Factory extends ContractFactory<
  CountdownBettingMarketInstance,
  CountdownBettingMarketTypes.Fields
> {
  encodeFields(fields: CountdownBettingMarketTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      []
    );
  }

  eventIndex = {
    BetPlaced: 0,
    RoundFinalized: 1,
    Claimed: 2,
    CarryOverRolled: 3,
  };
  consts = {
    MIN_BET: BigInt("100000000000000000"),
    THIRTY_MINUTES_MS: BigInt("1800000"),
    ErrorCodes: {
      BetTooSmall: BigInt("0"),
      RoundMismatch: BigInt("1"),
      RoundClosed: BigInt("2"),
      BettingWindowClosed: BigInt("4"),
      NotFinalized: BigInt("5"),
      NoBet: BigInt("6"),
      RoundNotSettled: BigInt("7"),
      AlreadyFinalized: BigInt("8"),
      InvalidPoolState: BigInt("9"),
    },
  };

  at(address: string): CountdownBettingMarketInstance {
    return new CountdownBettingMarketInstance(address);
  }

  tests = {
    placeBet: async (
      params: TestContractParams<
        CountdownBettingMarketTypes.Fields,
        { roundId: bigint; target: Address; amount: bigint },
        CountdownBettingMarketTypes.Maps
      >
    ): Promise<TestContractResult<null, CountdownBettingMarketTypes.Maps>> => {
      return testMethod(this, "placeBet", params, getContractByCodeHash);
    },
    finalizeRound: async (
      params: TestContractParams<
        CountdownBettingMarketTypes.Fields,
        { roundId: bigint },
        CountdownBettingMarketTypes.Maps
      >
    ): Promise<TestContractResult<null, CountdownBettingMarketTypes.Maps>> => {
      return testMethod(this, "finalizeRound", params, getContractByCodeHash);
    },
    claim: async (
      params: TestContractParams<
        CountdownBettingMarketTypes.Fields,
        { roundId: bigint },
        CountdownBettingMarketTypes.Maps
      >
    ): Promise<TestContractResult<null, CountdownBettingMarketTypes.Maps>> => {
      return testMethod(this, "claim", params, getContractByCodeHash);
    },
    getRoundPools: async (
      params: TestContractParams<
        CountdownBettingMarketTypes.Fields,
        { roundId: bigint; target: Address },
        CountdownBettingMarketTypes.Maps
      >
    ): Promise<
      TestContractResult<[bigint, bigint], CountdownBettingMarketTypes.Maps>
    > => {
      return testMethod(this, "getRoundPools", params, getContractByCodeHash);
    },
    getUserBet: async (
      params: TestContractParams<
        CountdownBettingMarketTypes.Fields,
        { roundId: bigint; bettor: Address },
        CountdownBettingMarketTypes.Maps
      >
    ): Promise<
      TestContractResult<
        [boolean, Address, bigint],
        CountdownBettingMarketTypes.Maps
      >
    > => {
      return testMethod(this, "getUserBet", params, getContractByCodeHash);
    },
    quotePayout: async (
      params: TestContractParams<
        CountdownBettingMarketTypes.Fields,
        { roundId: bigint; target: Address; amount: bigint },
        CountdownBettingMarketTypes.Maps
      >
    ): Promise<
      TestContractResult<bigint, CountdownBettingMarketTypes.Maps>
    > => {
      return testMethod(this, "quotePayout", params, getContractByCodeHash);
    },
    getClaimablePayout: async (
      params: TestContractParams<
        CountdownBettingMarketTypes.Fields,
        { roundId: bigint; target: Address; betAmount: bigint },
        CountdownBettingMarketTypes.Maps
      >
    ): Promise<
      TestContractResult<bigint, CountdownBettingMarketTypes.Maps>
    > => {
      return testMethod(
        this,
        "getClaimablePayout",
        params,
        getContractByCodeHash
      );
    },
  };

  stateForTest(
    initFields: CountdownBettingMarketTypes.Fields,
    asset?: Asset,
    address?: string,
    maps?: CountdownBettingMarketTypes.Maps
  ) {
    return this.stateForTest_(initFields, asset, address, maps);
  }
}

// Use this object to test and deploy the contract
export const CountdownBettingMarket = new Factory(
  Contract.fromJson(
    CountdownBettingMarketContractJson,
    "=5+546=1-1+6=1-2=2+919=1-3+9bd=1-2=1+18=1+ad=1-2=1-1+b6=1-5=12-2+e0=197-1+3=46+7a7e0214696e73657274206174206d617020706174683a2000=339-1+7=127-1+b=38+7a7e021472656d6f7665206174206d617020706174683a2000=201-1+b=38+7a7e021472656d6f7665206174206d617020706174683a2000=69-1+d=131-1+b=38+7a7e0214696e73657274206174206d617020706174683a2000=161-1+b=38+7a7e0214696e73657274206174206d617020706174683a2000=117-1+a=38+7a7e0214696e73657274206174206d617020706174683a2000=50+7a7e0214696e73657274206174206d617020706174683a2000=141-1+b=38+7a7e0214696e73657274206174206d617020706174683a2000=15-1+e=38+7a7e021472656d6f7665206174206d617020706174683a2000=44+7a7e021472656d6f7665206174206d617020706174683a2000=103-1+b=38+7a7e021472656d6f7665206174206d617020706174683a2000=93-1+c=376+7a7e0214696e73657274206174206d617020706174683a2000=41-1+c=560+7a7e021472656d6f7665206174206d617020706174683a2000=44+7a7e021472656d6f7665206174206d617020706174683a2000=45-1+3=59-1+b=38+7a7e021472656d6f7665206174206d617020706174683a2000=158-2+4025=38+7a7e021472656d6f7665206174206d617020706174683a2000=43-1+a=38+7a7e021472656d6f7665206174206d617020706174683a2000=44+7a7e021472656d6f7665206174206d617020706174683a2000=1270",
    "6903baf4da82f9ee16d3cfbd6dc30e91f5e867b61845e946e3d7a399735cd52c",
    []
  )
);
registerContract(CountdownBettingMarket);

// Use this class to interact with the blockchain
export class CountdownBettingMarketInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  maps = {
    totalPoolByRound: new RalphMap<HexString, bigint>(
      CountdownBettingMarket.contract,
      this.contractId,
      "totalPoolByRound"
    ),
    poolByRoundAndTarget: new RalphMap<HexString, bigint>(
      CountdownBettingMarket.contract,
      this.contractId,
      "poolByRoundAndTarget"
    ),
    userBetByRoundAndBettor: new RalphMap<HexString, bigint>(
      CountdownBettingMarket.contract,
      this.contractId,
      "userBetByRoundAndBettor"
    ),
    userTargetByRoundAndBettor: new RalphMap<HexString, Address>(
      CountdownBettingMarket.contract,
      this.contractId,
      "userTargetByRoundAndBettor"
    ),
    winnerByRound: new RalphMap<HexString, Address>(
      CountdownBettingMarket.contract,
      this.contractId,
      "winnerByRound"
    ),
    bettorCountByRound: new RalphMap<HexString, bigint>(
      CountdownBettingMarket.contract,
      this.contractId,
      "bettorCountByRound"
    ),
  };

  async fetchState(): Promise<CountdownBettingMarketTypes.State> {
    return fetchContractState(CountdownBettingMarket, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeBetPlacedEvent(
    options: EventSubscribeOptions<CountdownBettingMarketTypes.BetPlacedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      CountdownBettingMarket.contract,
      this,
      options,
      "BetPlaced",
      fromCount
    );
  }

  subscribeRoundFinalizedEvent(
    options: EventSubscribeOptions<CountdownBettingMarketTypes.RoundFinalizedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      CountdownBettingMarket.contract,
      this,
      options,
      "RoundFinalized",
      fromCount
    );
  }

  subscribeClaimedEvent(
    options: EventSubscribeOptions<CountdownBettingMarketTypes.ClaimedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      CountdownBettingMarket.contract,
      this,
      options,
      "Claimed",
      fromCount
    );
  }

  subscribeCarryOverRolledEvent(
    options: EventSubscribeOptions<CountdownBettingMarketTypes.CarryOverRolledEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      CountdownBettingMarket.contract,
      this,
      options,
      "CarryOverRolled",
      fromCount
    );
  }

  subscribeAllEvents(
    options: EventSubscribeOptions<
      | CountdownBettingMarketTypes.BetPlacedEvent
      | CountdownBettingMarketTypes.RoundFinalizedEvent
      | CountdownBettingMarketTypes.ClaimedEvent
      | CountdownBettingMarketTypes.CarryOverRolledEvent
    >,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvents(
      CountdownBettingMarket.contract,
      this,
      options,
      fromCount
    );
  }

  view = {
    placeBet: async (
      params: CountdownBettingMarketTypes.CallMethodParams<"placeBet">
    ): Promise<CountdownBettingMarketTypes.CallMethodResult<"placeBet">> => {
      return callMethod(
        CountdownBettingMarket,
        this,
        "placeBet",
        params,
        getContractByCodeHash
      );
    },
    finalizeRound: async (
      params: CountdownBettingMarketTypes.CallMethodParams<"finalizeRound">
    ): Promise<
      CountdownBettingMarketTypes.CallMethodResult<"finalizeRound">
    > => {
      return callMethod(
        CountdownBettingMarket,
        this,
        "finalizeRound",
        params,
        getContractByCodeHash
      );
    },
    claim: async (
      params: CountdownBettingMarketTypes.CallMethodParams<"claim">
    ): Promise<CountdownBettingMarketTypes.CallMethodResult<"claim">> => {
      return callMethod(
        CountdownBettingMarket,
        this,
        "claim",
        params,
        getContractByCodeHash
      );
    },
    getRoundPools: async (
      params: CountdownBettingMarketTypes.CallMethodParams<"getRoundPools">
    ): Promise<
      CountdownBettingMarketTypes.CallMethodResult<"getRoundPools">
    > => {
      return callMethod(
        CountdownBettingMarket,
        this,
        "getRoundPools",
        params,
        getContractByCodeHash
      );
    },
    getUserBet: async (
      params: CountdownBettingMarketTypes.CallMethodParams<"getUserBet">
    ): Promise<CountdownBettingMarketTypes.CallMethodResult<"getUserBet">> => {
      return callMethod(
        CountdownBettingMarket,
        this,
        "getUserBet",
        params,
        getContractByCodeHash
      );
    },
    quotePayout: async (
      params: CountdownBettingMarketTypes.CallMethodParams<"quotePayout">
    ): Promise<CountdownBettingMarketTypes.CallMethodResult<"quotePayout">> => {
      return callMethod(
        CountdownBettingMarket,
        this,
        "quotePayout",
        params,
        getContractByCodeHash
      );
    },
    getClaimablePayout: async (
      params: CountdownBettingMarketTypes.CallMethodParams<"getClaimablePayout">
    ): Promise<
      CountdownBettingMarketTypes.CallMethodResult<"getClaimablePayout">
    > => {
      return callMethod(
        CountdownBettingMarket,
        this,
        "getClaimablePayout",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    placeBet: async (
      params: CountdownBettingMarketTypes.SignExecuteMethodParams<"placeBet">
    ): Promise<
      CountdownBettingMarketTypes.SignExecuteMethodResult<"placeBet">
    > => {
      return signExecuteMethod(
        CountdownBettingMarket,
        this,
        "placeBet",
        params
      );
    },
    finalizeRound: async (
      params: CountdownBettingMarketTypes.SignExecuteMethodParams<"finalizeRound">
    ): Promise<
      CountdownBettingMarketTypes.SignExecuteMethodResult<"finalizeRound">
    > => {
      return signExecuteMethod(
        CountdownBettingMarket,
        this,
        "finalizeRound",
        params
      );
    },
    claim: async (
      params: CountdownBettingMarketTypes.SignExecuteMethodParams<"claim">
    ): Promise<
      CountdownBettingMarketTypes.SignExecuteMethodResult<"claim">
    > => {
      return signExecuteMethod(CountdownBettingMarket, this, "claim", params);
    },
    getRoundPools: async (
      params: CountdownBettingMarketTypes.SignExecuteMethodParams<"getRoundPools">
    ): Promise<
      CountdownBettingMarketTypes.SignExecuteMethodResult<"getRoundPools">
    > => {
      return signExecuteMethod(
        CountdownBettingMarket,
        this,
        "getRoundPools",
        params
      );
    },
    getUserBet: async (
      params: CountdownBettingMarketTypes.SignExecuteMethodParams<"getUserBet">
    ): Promise<
      CountdownBettingMarketTypes.SignExecuteMethodResult<"getUserBet">
    > => {
      return signExecuteMethod(
        CountdownBettingMarket,
        this,
        "getUserBet",
        params
      );
    },
    quotePayout: async (
      params: CountdownBettingMarketTypes.SignExecuteMethodParams<"quotePayout">
    ): Promise<
      CountdownBettingMarketTypes.SignExecuteMethodResult<"quotePayout">
    > => {
      return signExecuteMethod(
        CountdownBettingMarket,
        this,
        "quotePayout",
        params
      );
    },
    getClaimablePayout: async (
      params: CountdownBettingMarketTypes.SignExecuteMethodParams<"getClaimablePayout">
    ): Promise<
      CountdownBettingMarketTypes.SignExecuteMethodResult<"getClaimablePayout">
    > => {
      return signExecuteMethod(
        CountdownBettingMarket,
        this,
        "getClaimablePayout",
        params
      );
    },
  };

  async multicall<Calls extends CountdownBettingMarketTypes.MultiCallParams>(
    calls: Calls
  ): Promise<CountdownBettingMarketTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends CountdownBettingMarketTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<CountdownBettingMarketTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | CountdownBettingMarketTypes.MultiCallParams
      | CountdownBettingMarketTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      CountdownBettingMarket,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
