/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as CountdownGameContractJson } from "../CountdownGame.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";

// Custom types for the contract
export namespace CountdownGameTypes {
  export type Fields = {
    basePlayCost: bigint;
    currentLeader: Address;
    currentPot: bigint;
    currentDurationMs: bigint;
    deadlineMs: bigint;
    savingsPot: bigint;
    roundActive: boolean;
    currentPlayCost: bigint;
    currentRoundId: bigint;
    lastSettledRoundId: bigint;
    lastSettledWinner: Address;
  };

  export type State = ContractState<Fields>;

  export type PlayedEvent = ContractEvent<{
    roundId: bigint;
    player: Address;
    roundPot: bigint;
    deadlineMs: bigint;
    durationMs: bigint;
    playCost: bigint;
  }>;
  export type RoundSettledEvent = ContractEvent<{
    winner: Address;
    winnerPayout: bigint;
    savingsAdded: bigint;
  }>;
  export type RoundStartedEvent = ContractEvent<{
    roundId: bigint;
    starter: Address;
    deadlineMs: bigint;
  }>;

  export interface CallMethodTable {
    play: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    playDouble: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    settleRound: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    getRoundSnapshot: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<[boolean, bigint, bigint, Address]>;
    };
    getLastSettledRound: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<[bigint, Address]>;
    };
    continueRound: {
      params: CallContractParams<{
        caller: Address;
        now: bigint;
        playCost: bigint;
        isDouble: boolean;
      }>;
      result: CallContractResult<null>;
    };
    settleExpiredRound: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    startRound: {
      params: CallContractParams<{ caller: Address; now: bigint }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    play: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    playDouble: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    settleRound: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getRoundSnapshot: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getLastSettledRound: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    continueRound: {
      params: SignExecuteContractMethodParams<{
        caller: Address;
        now: bigint;
        playCost: bigint;
        isDouble: boolean;
      }>;
      result: SignExecuteScriptTxResult;
    };
    settleExpiredRound: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    startRound: {
      params: SignExecuteContractMethodParams<{ caller: Address; now: bigint }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  CountdownGameInstance,
  CountdownGameTypes.Fields
> {
  encodeFields(fields: CountdownGameTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      []
    );
  }

  eventIndex = { Played: 0, RoundSettled: 1, RoundStarted: 2 };
  consts = {
    INITIAL_DURATION_MS: BigInt("63891936000000"),
    THIRTY_SECONDS_MS: BigInt("30000"),
    ErrorCodes: {
      InvalidDuration: BigInt("0"),
      RoundNotActive: BigInt("1"),
      InvalidBasePlayCost: BigInt("2"),
    },
  };

  at(address: string): CountdownGameInstance {
    return new CountdownGameInstance(address);
  }

  tests = {
    play: async (
      params: Omit<
        TestContractParamsWithoutMaps<CountdownGameTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "play", params, getContractByCodeHash);
    },
    playDouble: async (
      params: Omit<
        TestContractParamsWithoutMaps<CountdownGameTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "playDouble", params, getContractByCodeHash);
    },
    settleRound: async (
      params: Omit<
        TestContractParamsWithoutMaps<CountdownGameTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "settleRound", params, getContractByCodeHash);
    },
    getRoundSnapshot: async (
      params: Omit<
        TestContractParamsWithoutMaps<CountdownGameTypes.Fields, never>,
        "args"
      >
    ): Promise<
      TestContractResultWithoutMaps<[boolean, bigint, bigint, Address]>
    > => {
      return testMethod(
        this,
        "getRoundSnapshot",
        params,
        getContractByCodeHash
      );
    },
    getLastSettledRound: async (
      params: Omit<
        TestContractParamsWithoutMaps<CountdownGameTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<[bigint, Address]>> => {
      return testMethod(
        this,
        "getLastSettledRound",
        params,
        getContractByCodeHash
      );
    },
    continueRound: async (
      params: TestContractParamsWithoutMaps<
        CountdownGameTypes.Fields,
        { caller: Address; now: bigint; playCost: bigint; isDouble: boolean }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "continueRound", params, getContractByCodeHash);
    },
    settleExpiredRound: async (
      params: Omit<
        TestContractParamsWithoutMaps<CountdownGameTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "settleExpiredRound",
        params,
        getContractByCodeHash
      );
    },
    startRound: async (
      params: TestContractParamsWithoutMaps<
        CountdownGameTypes.Fields,
        { caller: Address; now: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "startRound", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: CountdownGameTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const CountdownGame = new Factory(
  Contract.fromJson(
    CountdownGameContractJson,
    "",
    "e068f1ee65e893c05a91910b0e24d7e0a596f719bd575c041c00f90a544d9f2e",
    []
  )
);
registerContract(CountdownGame);

// Use this class to interact with the blockchain
export class CountdownGameInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<CountdownGameTypes.State> {
    return fetchContractState(CountdownGame, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribePlayedEvent(
    options: EventSubscribeOptions<CountdownGameTypes.PlayedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      CountdownGame.contract,
      this,
      options,
      "Played",
      fromCount
    );
  }

  subscribeRoundSettledEvent(
    options: EventSubscribeOptions<CountdownGameTypes.RoundSettledEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      CountdownGame.contract,
      this,
      options,
      "RoundSettled",
      fromCount
    );
  }

  subscribeRoundStartedEvent(
    options: EventSubscribeOptions<CountdownGameTypes.RoundStartedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      CountdownGame.contract,
      this,
      options,
      "RoundStarted",
      fromCount
    );
  }

  subscribeAllEvents(
    options: EventSubscribeOptions<
      | CountdownGameTypes.PlayedEvent
      | CountdownGameTypes.RoundSettledEvent
      | CountdownGameTypes.RoundStartedEvent
    >,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvents(
      CountdownGame.contract,
      this,
      options,
      fromCount
    );
  }

  view = {
    play: async (
      params?: CountdownGameTypes.CallMethodParams<"play">
    ): Promise<CountdownGameTypes.CallMethodResult<"play">> => {
      return callMethod(
        CountdownGame,
        this,
        "play",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    playDouble: async (
      params?: CountdownGameTypes.CallMethodParams<"playDouble">
    ): Promise<CountdownGameTypes.CallMethodResult<"playDouble">> => {
      return callMethod(
        CountdownGame,
        this,
        "playDouble",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    settleRound: async (
      params?: CountdownGameTypes.CallMethodParams<"settleRound">
    ): Promise<CountdownGameTypes.CallMethodResult<"settleRound">> => {
      return callMethod(
        CountdownGame,
        this,
        "settleRound",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getRoundSnapshot: async (
      params?: CountdownGameTypes.CallMethodParams<"getRoundSnapshot">
    ): Promise<CountdownGameTypes.CallMethodResult<"getRoundSnapshot">> => {
      return callMethod(
        CountdownGame,
        this,
        "getRoundSnapshot",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getLastSettledRound: async (
      params?: CountdownGameTypes.CallMethodParams<"getLastSettledRound">
    ): Promise<CountdownGameTypes.CallMethodResult<"getLastSettledRound">> => {
      return callMethod(
        CountdownGame,
        this,
        "getLastSettledRound",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    continueRound: async (
      params: CountdownGameTypes.CallMethodParams<"continueRound">
    ): Promise<CountdownGameTypes.CallMethodResult<"continueRound">> => {
      return callMethod(
        CountdownGame,
        this,
        "continueRound",
        params,
        getContractByCodeHash
      );
    },
    settleExpiredRound: async (
      params?: CountdownGameTypes.CallMethodParams<"settleExpiredRound">
    ): Promise<CountdownGameTypes.CallMethodResult<"settleExpiredRound">> => {
      return callMethod(
        CountdownGame,
        this,
        "settleExpiredRound",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    startRound: async (
      params: CountdownGameTypes.CallMethodParams<"startRound">
    ): Promise<CountdownGameTypes.CallMethodResult<"startRound">> => {
      return callMethod(
        CountdownGame,
        this,
        "startRound",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    play: async (
      params: CountdownGameTypes.SignExecuteMethodParams<"play">
    ): Promise<CountdownGameTypes.SignExecuteMethodResult<"play">> => {
      return signExecuteMethod(CountdownGame, this, "play", params);
    },
    playDouble: async (
      params: CountdownGameTypes.SignExecuteMethodParams<"playDouble">
    ): Promise<CountdownGameTypes.SignExecuteMethodResult<"playDouble">> => {
      return signExecuteMethod(CountdownGame, this, "playDouble", params);
    },
    settleRound: async (
      params: CountdownGameTypes.SignExecuteMethodParams<"settleRound">
    ): Promise<CountdownGameTypes.SignExecuteMethodResult<"settleRound">> => {
      return signExecuteMethod(CountdownGame, this, "settleRound", params);
    },
    getRoundSnapshot: async (
      params: CountdownGameTypes.SignExecuteMethodParams<"getRoundSnapshot">
    ): Promise<
      CountdownGameTypes.SignExecuteMethodResult<"getRoundSnapshot">
    > => {
      return signExecuteMethod(CountdownGame, this, "getRoundSnapshot", params);
    },
    getLastSettledRound: async (
      params: CountdownGameTypes.SignExecuteMethodParams<"getLastSettledRound">
    ): Promise<
      CountdownGameTypes.SignExecuteMethodResult<"getLastSettledRound">
    > => {
      return signExecuteMethod(
        CountdownGame,
        this,
        "getLastSettledRound",
        params
      );
    },
    continueRound: async (
      params: CountdownGameTypes.SignExecuteMethodParams<"continueRound">
    ): Promise<CountdownGameTypes.SignExecuteMethodResult<"continueRound">> => {
      return signExecuteMethod(CountdownGame, this, "continueRound", params);
    },
    settleExpiredRound: async (
      params: CountdownGameTypes.SignExecuteMethodParams<"settleExpiredRound">
    ): Promise<
      CountdownGameTypes.SignExecuteMethodResult<"settleExpiredRound">
    > => {
      return signExecuteMethod(
        CountdownGame,
        this,
        "settleExpiredRound",
        params
      );
    },
    startRound: async (
      params: CountdownGameTypes.SignExecuteMethodParams<"startRound">
    ): Promise<CountdownGameTypes.SignExecuteMethodResult<"startRound">> => {
      return signExecuteMethod(CountdownGame, this, "startRound", params);
    },
  };

  async multicall<Calls extends CountdownGameTypes.MultiCallParams>(
    calls: Calls
  ): Promise<CountdownGameTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends CountdownGameTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<CountdownGameTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | CountdownGameTypes.MultiCallParams
      | CountdownGameTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      CountdownGame,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
